version: '3'
services:
  listings_service:
    build: ./listings_service
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: app.py
      AWS_ACCESS_KEY_ID: AKIA5FCD6UKREQOSSEOW
      AWS_SECRET_ACCESS_KEY: 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
      AWS_S3_BUCKET_NAME: uoft-secondhand-hub-rush-listings
      AWS_S3_REGION: us-east-2
    command: flask run --host=0.0.0.0 --port=5000

  ratings_service:
    build: ./rating_service
    ports:
      - "5002:5000"
    environment:
      FLASK_APP: app.py
    command: flask run --host=0.0.0.0 --port=5000
